services:
  - type: web
    name: worldbeach-backend
    runtime: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: World Beach
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://worldbeach-backend.onrender.com
      - key: ASSET_URL
        value: https://worldbeach-backend.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: RUN_MIGRATIONS
        value: "true"
      - key: RUN_ADMIN_SEEDER
        value: "true"
      - key: ADMIN_NAME
        value: Admin
      - key: ADMIN_EMAIL
        value: admin@worldbeach.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: worldbeach-db
          property: connectionString
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: s3
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: auto
      - key: AWS_BUCKET
        sync: false
      - key: AWS_URL
        sync: false
      - key: AWS_ENDPOINT
        sync: false
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: "true"
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_UPLOAD_PRESET
        sync: false
      - key: CLOUDINARY_NOTIFICATION_URL
        sync: false
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SANCTUM_STATEFUL_DOMAINS
        value: worldbeach-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://worldbeach-backend.onrender.com
      - key: CORS_SUPPORTS_CREDENTIALS
        value: "true"

databases:
  - name: worldbeach-db
    plan: free
